### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AndiLavera** [gitlato/mochi#3]
This is a general roadmap, things are subject to change. Just a little insight on development.

Version 0.2.0
- [x] Lockable 
- Users have X amount of try's to sign in otherwise the account is locked
- Email with unlock instructions are sent out
- [x] Invitable
- Users can invite other users

Version 0.3.0
- [x] Controller Specs
- [x] Crystal 0.35.1
- [ ] Remove CLI & move to separate shard

Version 0.4.0
- [ ] Give Omniauthable a makeover
  - [ ] Add providers
    - [ ] Google
    - [ ] Gitlab
    - [ ] Apple
  - [ ] Solidify api
  - [ ] Document code
- [ ] Overhaul all documentation

Version 0.4.1
- [ ] Passwordless sign in
- [ ] 2FA

Version XX
- [ ] Api support for controllers
- [ ] JWT

**Comment by cimtico** [comment]
Is this project still under development? It looks interesting, but it seems it is either broken or missing instructions for the latest amber framework.
